package com.autismindd.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.autismindd.dao.User;
import com.autismindd.dao.TaskPack;
import com.autismindd.dao.Task;
import com.autismindd.dao.Item;
import com.autismindd.dao.Result;
import com.autismindd.dao.FirstLayer;
import com.autismindd.dao.Level;
import com.autismindd.dao.ErrorUserLog;
import com.autismindd.dao.Star;
import com.autismindd.dao.FirstLayerTaskImage;
import com.autismindd.dao.TimeStatistics;
import com.autismindd.dao.GiftTbl;

import com.autismindd.dao.UserDao;
import com.autismindd.dao.TaskPackDao;
import com.autismindd.dao.TaskDao;
import com.autismindd.dao.ItemDao;
import com.autismindd.dao.ResultDao;
import com.autismindd.dao.FirstLayerDao;
import com.autismindd.dao.LevelDao;
import com.autismindd.dao.ErrorUserLogDao;
import com.autismindd.dao.StarDao;
import com.autismindd.dao.FirstLayerTaskImageDao;
import com.autismindd.dao.TimeStatisticsDao;
import com.autismindd.dao.GiftTblDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig taskPackDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig resultDaoConfig;
    private final DaoConfig firstLayerDaoConfig;
    private final DaoConfig levelDaoConfig;
    private final DaoConfig errorUserLogDaoConfig;
    private final DaoConfig starDaoConfig;
    private final DaoConfig firstLayerTaskImageDaoConfig;
    private final DaoConfig timeStatisticsDaoConfig;
    private final DaoConfig giftTblDaoConfig;

    private final UserDao userDao;
    private final TaskPackDao taskPackDao;
    private final TaskDao taskDao;
    private final ItemDao itemDao;
    private final ResultDao resultDao;
    private final FirstLayerDao firstLayerDao;
    private final LevelDao levelDao;
    private final ErrorUserLogDao errorUserLogDao;
    private final StarDao starDao;
    private final FirstLayerTaskImageDao firstLayerTaskImageDao;
    private final TimeStatisticsDao timeStatisticsDao;
    private final GiftTblDao giftTblDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        taskPackDaoConfig = daoConfigMap.get(TaskPackDao.class).clone();
        taskPackDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        resultDaoConfig = daoConfigMap.get(ResultDao.class).clone();
        resultDaoConfig.initIdentityScope(type);

        firstLayerDaoConfig = daoConfigMap.get(FirstLayerDao.class).clone();
        firstLayerDaoConfig.initIdentityScope(type);

        levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
        levelDaoConfig.initIdentityScope(type);

        errorUserLogDaoConfig = daoConfigMap.get(ErrorUserLogDao.class).clone();
        errorUserLogDaoConfig.initIdentityScope(type);

        starDaoConfig = daoConfigMap.get(StarDao.class).clone();
        starDaoConfig.initIdentityScope(type);

        firstLayerTaskImageDaoConfig = daoConfigMap.get(FirstLayerTaskImageDao.class).clone();
        firstLayerTaskImageDaoConfig.initIdentityScope(type);

        timeStatisticsDaoConfig = daoConfigMap.get(TimeStatisticsDao.class).clone();
        timeStatisticsDaoConfig.initIdentityScope(type);

        giftTblDaoConfig = daoConfigMap.get(GiftTblDao.class).clone();
        giftTblDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        taskPackDao = new TaskPackDao(taskPackDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        resultDao = new ResultDao(resultDaoConfig, this);
        firstLayerDao = new FirstLayerDao(firstLayerDaoConfig, this);
        levelDao = new LevelDao(levelDaoConfig, this);
        errorUserLogDao = new ErrorUserLogDao(errorUserLogDaoConfig, this);
        starDao = new StarDao(starDaoConfig, this);
        firstLayerTaskImageDao = new FirstLayerTaskImageDao(firstLayerTaskImageDaoConfig, this);
        timeStatisticsDao = new TimeStatisticsDao(timeStatisticsDaoConfig, this);
        giftTblDao = new GiftTblDao(giftTblDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(TaskPack.class, taskPackDao);
        registerDao(Task.class, taskDao);
        registerDao(Item.class, itemDao);
        registerDao(Result.class, resultDao);
        registerDao(FirstLayer.class, firstLayerDao);
        registerDao(Level.class, levelDao);
        registerDao(ErrorUserLog.class, errorUserLogDao);
        registerDao(Star.class, starDao);
        registerDao(FirstLayerTaskImage.class, firstLayerTaskImageDao);
        registerDao(TimeStatistics.class, timeStatisticsDao);
        registerDao(GiftTbl.class, giftTblDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        taskPackDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        resultDaoConfig.getIdentityScope().clear();
        firstLayerDaoConfig.getIdentityScope().clear();
        levelDaoConfig.getIdentityScope().clear();
        errorUserLogDaoConfig.getIdentityScope().clear();
        starDaoConfig.getIdentityScope().clear();
        firstLayerTaskImageDaoConfig.getIdentityScope().clear();
        timeStatisticsDaoConfig.getIdentityScope().clear();
        giftTblDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TaskPackDao getTaskPackDao() {
        return taskPackDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public ResultDao getResultDao() {
        return resultDao;
    }

    public FirstLayerDao getFirstLayerDao() {
        return firstLayerDao;
    }

    public LevelDao getLevelDao() {
        return levelDao;
    }

    public ErrorUserLogDao getErrorUserLogDao() {
        return errorUserLogDao;
    }

    public StarDao getStarDao() {
        return starDao;
    }

    public FirstLayerTaskImageDao getFirstLayerTaskImageDao() {
        return firstLayerTaskImageDao;
    }

    public TimeStatisticsDao getTimeStatisticsDao() {
        return timeStatisticsDao;
    }

    public GiftTblDao getGiftTblDao() {
        return giftTblDao;
    }

}
