package com.autismindd.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.autismindd.dao.ErrorUserLog;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ERROR_USER_LOG".
*/
public class ErrorUserLogDao extends AbstractDao<ErrorUserLog, Long> {

    public static final String TABLENAME = "ERROR_USER_LOG";

    /**
     * Properties of entity ErrorUserLog.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property FirstLayerTaskId = new Property(2, int.class, "firstLayerTaskId", false, "FIRST_LAYER_TASK_ID");
        public final static Property LevelTaskPackId = new Property(3, int.class, "levelTaskPackId", false, "LEVEL_TASK_PACK_ID");
        public final static Property ErrorTaskCount = new Property(4, Long.class, "errorTaskCount", false, "ERROR_TASK_COUNT");
    };


    public ErrorUserLogDao(DaoConfig config) {
        super(config);
    }
    
    public ErrorUserLogDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ERROR_USER_LOG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"FIRST_LAYER_TASK_ID\" INTEGER NOT NULL ," + // 2: firstLayerTaskId
                "\"LEVEL_TASK_PACK_ID\" INTEGER NOT NULL ," + // 3: levelTaskPackId
                "\"ERROR_TASK_COUNT\" INTEGER);"); // 4: errorTaskCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ERROR_USER_LOG\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ErrorUserLog entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getFirstLayerTaskId());
        stmt.bindLong(4, entity.getLevelTaskPackId());
 
        Long errorTaskCount = entity.getErrorTaskCount();
        if (errorTaskCount != null) {
            stmt.bindLong(5, errorTaskCount);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ErrorUserLog readEntity(Cursor cursor, int offset) {
        ErrorUserLog entity = new ErrorUserLog( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // firstLayerTaskId
            cursor.getInt(offset + 3), // levelTaskPackId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // errorTaskCount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ErrorUserLog entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setFirstLayerTaskId(cursor.getInt(offset + 2));
        entity.setLevelTaskPackId(cursor.getInt(offset + 3));
        entity.setErrorTaskCount(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ErrorUserLog entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ErrorUserLog entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
