package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ERROR_USER_LOG".
 */
public class ErrorUserLog {

    private Long id;
    private long userId;
    private int firstLayerTaskId;
    private int levelTaskPackId;
    private Long errorTaskCount;

    public ErrorUserLog() {
    }

    public ErrorUserLog(Long id) {
        this.id = id;
    }

    public ErrorUserLog(Long id, long userId, int firstLayerTaskId, int levelTaskPackId, Long errorTaskCount) {
        this.id = id;
        this.userId = userId;
        this.firstLayerTaskId = firstLayerTaskId;
        this.levelTaskPackId = levelTaskPackId;
        this.errorTaskCount = errorTaskCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getFirstLayerTaskId() {
        return firstLayerTaskId;
    }

    public void setFirstLayerTaskId(int firstLayerTaskId) {
        this.firstLayerTaskId = firstLayerTaskId;
    }

    public int getLevelTaskPackId() {
        return levelTaskPackId;
    }

    public void setLevelTaskPackId(int levelTaskPackId) {
        this.levelTaskPackId = levelTaskPackId;
    }

    public Long getErrorTaskCount() {
        return errorTaskCount;
    }

    public void setErrorTaskCount(Long errorTaskCount) {
        this.errorTaskCount = errorTaskCount;
    }

}
