package com.autismindd.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.autismindd.dao.FirstLayerTaskImage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FIRST_LAYER_TASK_IMAGE".
*/
public class FirstLayerTaskImageDao extends AbstractDao<FirstLayerTaskImage, Long> {

    public static final String TABLENAME = "FIRST_LAYER_TASK_IMAGE";

    /**
     * Properties of entity FirstLayerTaskImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FirstLayerTaskId = new Property(1, int.class, "firstLayerTaskId", false, "FIRST_LAYER_TASK_ID");
        public final static Property FirstLayerTaskImages = new Property(2, String.class, "firstLayerTaskImages", false, "FIRST_LAYER_TASK_IMAGES");
        public final static Property FirstLayerTaskDes = new Property(3, String.class, "firstLayerTaskDes", false, "FIRST_LAYER_TASK_DES");
    };


    public FirstLayerTaskImageDao(DaoConfig config) {
        super(config);
    }
    
    public FirstLayerTaskImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FIRST_LAYER_TASK_IMAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FIRST_LAYER_TASK_ID\" INTEGER NOT NULL ," + // 1: firstLayerTaskId
                "\"FIRST_LAYER_TASK_IMAGES\" TEXT NOT NULL ," + // 2: firstLayerTaskImages
                "\"FIRST_LAYER_TASK_DES\" TEXT NOT NULL );"); // 3: firstLayerTaskDes
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FIRST_LAYER_TASK_IMAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FirstLayerTaskImage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getFirstLayerTaskId());
        stmt.bindString(3, entity.getFirstLayerTaskImages());
        stmt.bindString(4, entity.getFirstLayerTaskDes());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FirstLayerTaskImage readEntity(Cursor cursor, int offset) {
        FirstLayerTaskImage entity = new FirstLayerTaskImage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // firstLayerTaskId
            cursor.getString(offset + 2), // firstLayerTaskImages
            cursor.getString(offset + 3) // firstLayerTaskDes
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FirstLayerTaskImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFirstLayerTaskId(cursor.getInt(offset + 1));
        entity.setFirstLayerTaskImages(cursor.getString(offset + 2));
        entity.setFirstLayerTaskDes(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FirstLayerTaskImage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FirstLayerTaskImage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
