package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FIRST_LAYER".
 */
public class FirstLayer {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String fileName;
    /** Not-null value. */
    private String imgUrl;
    private int firstLayerTaskID;
    private boolean locked;
    private boolean state;
    private java.util.Date createdAt;

    public FirstLayer() {
    }

    public FirstLayer(Long id) {
        this.id = id;
    }

    public FirstLayer(Long id, String name, String fileName, String imgUrl, int firstLayerTaskID, boolean locked, boolean state, java.util.Date createdAt) {
        this.id = id;
        this.name = name;
        this.fileName = fileName;
        this.imgUrl = imgUrl;
        this.firstLayerTaskID = firstLayerTaskID;
        this.locked = locked;
        this.state = state;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getFileName() {
        return fileName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /** Not-null value. */
    public String getImgUrl() {
        return imgUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public int getFirstLayerTaskID() {
        return firstLayerTaskID;
    }

    public void setFirstLayerTaskID(int firstLayerTaskID) {
        this.firstLayerTaskID = firstLayerTaskID;
    }

    public boolean getLocked() {
        return locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    public boolean getState() {
        return state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

}
