package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FIRST_LAYER_TASK_IMAGE".
 */
public class FirstLayerTaskImage {

    private Long id;
    private int firstLayerTaskId;
    /** Not-null value. */
    private String firstLayerTaskImages;
    /** Not-null value. */
    private String firstLayerTaskDes;

    public FirstLayerTaskImage() {
    }

    public FirstLayerTaskImage(Long id) {
        this.id = id;
    }

    public FirstLayerTaskImage(Long id, int firstLayerTaskId, String firstLayerTaskImages, String firstLayerTaskDes) {
        this.id = id;
        this.firstLayerTaskId = firstLayerTaskId;
        this.firstLayerTaskImages = firstLayerTaskImages;
        this.firstLayerTaskDes = firstLayerTaskDes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getFirstLayerTaskId() {
        return firstLayerTaskId;
    }

    public void setFirstLayerTaskId(int firstLayerTaskId) {
        this.firstLayerTaskId = firstLayerTaskId;
    }

    /** Not-null value. */
    public String getFirstLayerTaskImages() {
        return firstLayerTaskImages;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstLayerTaskImages(String firstLayerTaskImages) {
        this.firstLayerTaskImages = firstLayerTaskImages;
    }

    /** Not-null value. */
    public String getFirstLayerTaskDes() {
        return firstLayerTaskDes;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstLayerTaskDes(String firstLayerTaskDes) {
        this.firstLayerTaskDes = firstLayerTaskDes;
    }

}
