package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GIFT_TBL".
 */
public class GiftTbl {

    private Long id;
    private long userId;
    private long userKey;
    private int AppearPoint;
    private int AppearCount;

    public GiftTbl() {
    }

    public GiftTbl(Long id) {
        this.id = id;
    }

    public GiftTbl(Long id, long userId, long userKey, int AppearPoint, int AppearCount) {
        this.id = id;
        this.userId = userId;
        this.userKey = userKey;
        this.AppearPoint = AppearPoint;
        this.AppearCount = AppearCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getUserKey() {
        return userKey;
    }

    public void setUserKey(long userKey) {
        this.userKey = userKey;
    }

    public int getAppearPoint() {
        return AppearPoint;
    }

    public void setAppearPoint(int AppearPoint) {
        this.AppearPoint = AppearPoint;
    }

    public int getAppearCount() {
        return AppearCount;
    }

    public void setAppearCount(int AppearCount) {
        this.AppearCount = AppearCount;
    }

}
