package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LEVEL".
 */
public class Level {

    private Long id;
    private Long key;
    private Integer levelNumber;
    private Integer errorCount;
    private Integer efficient;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private long userId;
    private long taskPackId;
    private long lastTaskId;

    public Level() {
    }

    public Level(Long id) {
        this.id = id;
    }

    public Level(Long id, Long key, Integer levelNumber, Integer errorCount, Integer efficient, java.util.Date createdAt, java.util.Date updatedAt, long userId, long taskPackId, long lastTaskId) {
        this.id = id;
        this.key = key;
        this.levelNumber = levelNumber;
        this.errorCount = errorCount;
        this.efficient = efficient;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.userId = userId;
        this.taskPackId = taskPackId;
        this.lastTaskId = lastTaskId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getKey() {
        return key;
    }

    public void setKey(Long key) {
        this.key = key;
    }

    public Integer getLevelNumber() {
        return levelNumber;
    }

    public void setLevelNumber(Integer levelNumber) {
        this.levelNumber = levelNumber;
    }

    public Integer getErrorCount() {
        return errorCount;
    }

    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    public Integer getEfficient() {
        return efficient;
    }

    public void setEfficient(Integer efficient) {
        this.efficient = efficient;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getTaskPackId() {
        return taskPackId;
    }

    public void setTaskPackId(long taskPackId) {
        this.taskPackId = taskPackId;
    }

    public long getLastTaskId() {
        return lastTaskId;
    }

    public void setLastTaskId(long lastTaskId) {
        this.lastTaskId = lastTaskId;
    }

}
