package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STAR".
 */
public class Star {

    private Long id;
    private long userId;
    private int firstLayerTaskId;
    private int levelTaskPackId;
    private int levelStar;
    private int levelPoint;
    private long levelRT;
    private long levelDT;
    private long levelErrorPoint;

    public Star() {
    }

    public Star(Long id) {
        this.id = id;
    }

    public Star(Long id, long userId, int firstLayerTaskId, int levelTaskPackId, int levelStar, int levelPoint, long levelRT, long levelDT, long levelErrorPoint) {
        this.id = id;
        this.userId = userId;
        this.firstLayerTaskId = firstLayerTaskId;
        this.levelTaskPackId = levelTaskPackId;
        this.levelStar = levelStar;
        this.levelPoint = levelPoint;
        this.levelRT = levelRT;
        this.levelDT = levelDT;
        this.levelErrorPoint = levelErrorPoint;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getFirstLayerTaskId() {
        return firstLayerTaskId;
    }

    public void setFirstLayerTaskId(int firstLayerTaskId) {
        this.firstLayerTaskId = firstLayerTaskId;
    }

    public int getLevelTaskPackId() {
        return levelTaskPackId;
    }

    public void setLevelTaskPackId(int levelTaskPackId) {
        this.levelTaskPackId = levelTaskPackId;
    }

    public int getLevelStar() {
        return levelStar;
    }

    public void setLevelStar(int levelStar) {
        this.levelStar = levelStar;
    }

    public int getLevelPoint() {
        return levelPoint;
    }

    public void setLevelPoint(int levelPoint) {
        this.levelPoint = levelPoint;
    }

    public long getLevelRT() {
        return levelRT;
    }

    public void setLevelRT(long levelRT) {
        this.levelRT = levelRT;
    }

    public long getLevelDT() {
        return levelDT;
    }

    public void setLevelDT(long levelDT) {
        this.levelDT = levelDT;
    }

    public long getLevelErrorPoint() {
        return levelErrorPoint;
    }

    public void setLevelErrorPoint(long levelErrorPoint) {
        this.levelErrorPoint = levelErrorPoint;
    }

}
