package com.autismindd.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TIME_STATISTICS".
 */
public class TimeStatistics {

    private Long id;
    private long userKey;
    private int firstLayerTaskId;
    private int level;
    private long time;

    public TimeStatistics() {
    }

    public TimeStatistics(Long id) {
        this.id = id;
    }

    public TimeStatistics(Long id, long userKey, int firstLayerTaskId, int level, long time) {
        this.id = id;
        this.userKey = userKey;
        this.firstLayerTaskId = firstLayerTaskId;
        this.level = level;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserKey() {
        return userKey;
    }

    public void setUserKey(long userKey) {
        this.userKey = userKey;
    }

    public int getFirstLayerTaskId() {
        return firstLayerTaskId;
    }

    public void setFirstLayerTaskId(int firstLayerTaskId) {
        this.firstLayerTaskId = firstLayerTaskId;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
